### ISSUE TITLE
Email bounces

### ISSUE THREAD

**Issue by ErikBjare** [p13i/p13i.github.io#52]
Been trying to contact you, but emails to both p13i@stanford.edu (website) and <your.longer.name>@stanford.edu (sent from) bounce on me! 😬

**Comment by p13i** [comment]
Hi! Thanks for reaching out. What a coincidence: my Stanford email access
just expired (I graduated a week ago). Feel free to contact me at
***@***.*** I'll update my site now.

**Comment by p13i** [comment]
hi! pls do lmk if you'd still like to connect. gonna close this issue.
